[package]
name = "libmonero"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3.2"
rand = "0.8.5"
regex = "1.10.2"
