/*
 * This file is part of Monero Builders' library libmonero
 *
 * Copyright (c) 2023-2024, Monero Builders (monero.builders)
 * All Rights Reserved
 * The code is distributed under MIT license, see LICENSE file for details.
 * Generated by Monume
 *
 */

use super::languages::english::ENGLISHPOLYSEED;

pub(crate) struct WordsetPolyseed {
    pub name: &'static str,
    pub prefix_length: u8,
    pub words: [&'static str; 2048],
}

pub(crate) static WORDSETSPOLYSEED : [WordsetPolyseed; 1] = [
    ENGLISHPOLYSEED,
];