/*
 * This file is part of OpenMonero's Go library libmonero
 *
 * Copyright (c) 2023 OpenMonero
 * All Rights Reserved.
 * The code is distributed under MIT license, see LICENSE file for details.
 * Generated by OpenMonero on 10-07-2023.
 *
 */

package libmonero

// Struct of a given remote node
type Node struct {
  // TODO: Add Node struct
  host string
  port int
}
