/*
 * This file is part of OpenMonero's Go library libmonero
 *
 * Copyright (c) 2023 OpenMonero
 * All Rights Reserved.
 * The code is distributed under MIT license, see LICENSE file for details.
 * Generated by OpenMonero on 10-07-2023.
 *
 */

package libmonero

type Tx struct {
  // TODO: Add transaction struct
  recipientAddr string
  amount string
  senderAddr string
}

type SignedTx struct {
  // TODO: Add SignedTx struct
}

// SignTransaction : Signs the transaction with given private spend key and returns SignedTx
// Returns error if there has been an error
func SignTransaction(transaction Transaction, privateSpendKey string) (SignedTx, error) {
  // TODO: Implement SignTransaction
  return SignedTx, nil
}

// BroadcastTransaction : Broadcasts the given transaction to given remote node and returns transaction hash
// Returns error if there has been an error
func BroadcastTransaction(signedTx SignedTx, node Node) (string, error) {
  // TODO: Implement BroadcastTransaction
  return "", nil
}
