/*
 * This file is part of Monume's library libmonero
 *
 * Copyright (c) 2023 Monume
 * All Rights Reserved
 * The code is distributed under MIT license, see LICENSE file for details.
 * Generated by Monume
 *
 */

package libmonero

import "regexp"

func Version() string {
	return "0.1.2"
}

func ValidateAddress(address string) bool {
	match, _ := regexp.MatchString(`^4[0-9AB][1-9A-HJ-NP-Za-km-z]{93}$`, address)
	return match
}
