/*
 * This file is part of Monume's library libmonero
 *
 * Copyright (c) 2023 Monume
 * All Rights Reserved
 * The code is distributed under MIT license, see LICENSE file for details.
 * Generated by Monume
 *
 */

use regex::Regex;

// Returns true if given address is a valid Monero address
pub fn is_valid_addr(address: &str) -> bool {
    let r = Regex::new(r"^(4|8)[0-9a-zA-Z]{95}$").unwrap();
    r.is_match(address)
}