/*
 * This file is part of OpenMonero's library libmonero
 *
 * Copyright (c) 2023 OpenMonero
 * All Rights Reserved
 * The code is distributed under MIT license, see LICENSE file for details.
 * Generated by OpenMonero
 *
 */

package libmonero


func getBalance() {
	// TODO: Add getBalance function
}

func getTransactions() {
	// TODO: Add getTransactions function
}

func makeTransfer() {
	// TODO: Add makeTransfer function
}